name: mtse_dev
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip

  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - -f https://data.pyg.org/whl/torch-2.7.0+cu128.html
    - --config-settings editable-mode=strict

    - torch==2.7.0+cu128

    - -e ./
    - build

    # For developers' convenience
    - ipykernel
    - ipywidgets
