seed_everything: 0 # His seeds were 0,112,343
trainer:
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: ./

  max_epochs: 5 

  # TSE authors use model checkpointing for their stance training
  # But they use F1 score for just stance (not the targets)
  callbacks:

    # Calculate the stance F1
    - class_path: mtse.callbacks.StanceClassificationStatsCallback

    # Monitor the stance F1
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/stance/bimacro_f1
        mode: max
        filename: "epoch={epoch:02d}-bimacro_f1={val/stance/bimacro_f1:.3f}"
        auto_insert_metric_name: false

  # These are their settings, for both training and inference
  # Doesn't set these for target classification
  deterministic: true
  benchmark: false

model:
  class_path: mtse.modules.ClassicStanceClassifierModule
  init_args:
    targets_path: static/classic_merged_targets.txt
    stance_type: tri
data:
  class_path: mtse.data.PattDataModule
  init_args:
    # TSE authors cut the batch size down to 64 for the stance training
    batch_size: 64
    # Notice no target_pred_path values
    # They only uses GT targets during stance training
    train_patts: [data/classic/*.train.csv]
    val_patts:   [data/classic/*.val.csv]
    test_patts:  [data/classic/*.test.csv]