seed_everything: 0 # his seeds were 0,112,343
trainer:
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: ./

  # No early stopping-- He just does 5 epochs
  # Fixed five epochs from Him
  max_epochs: 5 

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/target/micro_f1
        mode: max
        filename: "epoch={epoch:02d}-micro_f1={val/target/micro_f1:.3f}"
        auto_insert_metric_name: false
    - class_path: mtse.callbacks.TargetClassificationStatsCallback
      init_args:
        n_classes: 19

  # He did gradient norm clipping to 1.
  gradient_clip_val: 1.
  gradient_clip_algorithm: norm

  # He didn't specify, so neither will we
  deterministic: null

model:
  class_path: mtse.modules.ClassicTargetClassifierModule
  init_args:
    targets_path: static/classic_merged_targets.txt
data:
  class_path: mtse.data.PattDataModule
  init_args:
    batch_size: 128
    transforms: [ {"class_path": "mtse.data.ClassicPreprocess"} ]
    train_patts: [data/classic/*.train.csv]
    val_patts:   [data/classic/*.val.csv]
    test_patts:  [data/classic/*.test.csv]