seed_everything: 0 # Li's seeds were 0,112,343
trainer:
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: ./

  # No early stopping-- Li just does 5 epochs
  # Fixed five epochs from Li
  max_epochs: 5 

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/target/micro_f1
        mode: max
        filename: "epoch={epoch:02d}-micro_f1={val/target/micro_f1:.3f}"
        auto_insert_metric_name: false

  # Li did gradient norm clipping to 1.
  gradient_clip_val: 1.
  gradient_clip_algorithm: norm

  # Li didn't specify, so neither will we
  deterministic: null

model:
  class_path: mtse.modules.LiTargetModule
  init_args:
    targets_path: static/li_merged_targets.txt
data:
  class_path: mtse.data.SplitDataModule
  init_args:
    batch_size: 128
    transforms: [ {"class_path": "mtse.data.LiPreprocess", "init_args": {"scrub_targets": true}} ]
    corpora:
      - class_path: mtse.data.StanceCorpus
        init_args:
          path: data/li_tse/raw_train_all_onecol.csv
          corpus_type: li
      - class_path: mtse.data.StanceCorpus
        init_args:
          path: data/li_tse/raw_val_all_onecol.csv
          corpus_type: li
    ratios: [ [1.0, 0.0, 0.0], [0.0, 1.0, 0.0] ]

    # corpora:
    #   - class_path: mtse.data.StanceCorpus
    #     init_args:
    #       path: data/li_tse/raw_val_all_onecol.csv
    #       corpus_type: li
    # ratios: [ [0.8, 0.2, 0.0] ]
