seed_everything: 0 
trainer:
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: ./

  callbacks:

    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/loss
        patience: 5
        mode: min

    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/loss
        mode: min
        filename: "epoch={epoch:02d}-loss={val/loss:.3f}"
        auto_insert_metric_name: false

  val_check_interval: 500
  max_time: "00:24:00:00"

model:
  # We only train the target generation portion
  class_path: mtse.modules.LiTargetGenerator

  init_args:
    targets_path: static/multiling_targets.txt # Doesn't matter here but have to supply it
    predict_targets: false
    # Supply embeddings path manually
    multilingual: true

data:
  class_path: mtse.data.SplitDataModule
  init_args:
    batch_size: 32

    corpora:
      - class_path: mtse.data.StanceCorpus
        init_args:
          path: data/kptimes/train.jsonl
          corpus_type: kptimes
          transforms: [ {"class_path": "mtse.data.LiPreprocess"} ]
          limit_n: 1000000
      - class_path: mtse.data.StanceCorpus
        init_args:
          path: data/kptimes/dev.jsonl
          corpus_type: kptimes
          transforms: [ {"class_path": "mtse.data.LiPreprocess"} ]
    ratios:
      - [1.0, 0.0, 0.0]
      - [0.0, 1.0, 0.0]

