# lightning.pytorch==2.5.0.post0
seed_everything: 1
trainer:
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: ./
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
              monitor: val_micro_f1
              mode: max
              patience: 10
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
              monitor: val_micro_f1
              mode: max
              filename: "{epoch:02d}-{val_micro_f1:.3f}"
