data:
  init_args:
    transforms:
      - class_path: mtse.data.TargetRename
        init_args:
          renames:
            "Emmanuel Macron": Macron
            "Marine LePen": Le Pen
            "Immigration": Immigration
            "IphoneSE": iPhone SE
            "Russia's counter-terrorism operations in Syria": Russia-Syria counter-terrorism
            "Allowing second births": Second births
            "Setting off firecrackers during the Spring Festival": Spring Festival firecrackers
            "Shenzhen bans motorcycles and imposes electricity restrictions": Shenzhen motorcycle ban
            "Sardinian Independence": Sardinia independence
            "Catalonian Independence": Catalonia independence