"Russia's counter-terrorism operations in Syria": "Russia"
"Setting off firecrackers during the Spring Festival": "Firecrackers"
"Shenzhen bans motorcycles and imposes electricity restrictions": "Shenzhen Laws"